# Generated by Django 5.2.11 on 2026-03-02 20:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FacultyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_name', models.CharField(max_length=200)),
                ('teacher_code', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('joining_date', models.DateField(blank=True, null=True)),
                ('school_name', models.CharField(default='LKC', max_length=100)),
                ('job_position', models.CharField(default='Teacher', max_length=100)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='faculty/')),
                ('work_phone', models.CharField(blank=True, max_length=30)),
                ('work_mobile', models.CharField(blank=True, max_length=30)),
                ('work_email', models.EmailField(blank=True, max_length=254)),
                ('work_location', models.CharField(blank=True, max_length=100)),
                ('street', models.CharField(blank=True, max_length=200)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('zip_code', models.CharField(blank=True, max_length=20)),
                ('country', models.CharField(default='Botswana', max_length=100)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('id_number', models.CharField(blank=True, max_length=50)),
                ('marital_status', models.CharField(blank=True, choices=[('single', 'Single'), ('married', 'Married'), ('divorced', 'Divorced'), ('widowed', 'Widowed')], max_length=10)),
                ('spouse_name', models.CharField(blank=True, max_length=200)),
                ('language_known', models.CharField(blank=True, max_length=200)),
                ('emergency_contact', models.CharField(blank=True, max_length=200)),
                ('emergency_phone', models.CharField(blank=True, max_length=30)),
                ('qualification', models.CharField(blank=True, max_length=200)),
                ('experience_years', models.IntegerField(default=0)),
                ('state', models.CharField(choices=[('active', 'Active'), ('on_leave', 'On Leave'), ('resigned', 'Resigned'), ('retired', 'Retired')], default='active', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teachers', to='core.department')),
                ('subjects', models.ManyToManyField(blank=True, related_name='teachers', to='core.subject')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='faculty_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Teacher',
                'ordering': ['teacher_name'],
            },
        ),
    ]
